name: Main Workflow

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  generate-tests:
    uses: ./.github/workflows/generate-exploratory.yml
    with:
      website-url: ${{ vars.TESTDRIVER_WEBSITE }}
    secrets:
      key: ${{ secrets.TESTDRIVER_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    needs: generate-tests
    uses: ./.github/workflows/generate-regressions.yml
    with:
      base-branch: ${{ needs.generate-tests.outputs.pr-branch }}
      website-url: ${{ vars.TESTDRIVER_WEBSITE }}
    secrets:
      key: ${{ secrets.TESTDRIVER_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
